### ISSUE TITLE
Error running Python 3.11.1

### ISSUE THREAD

**Issue by riesebie** [Tinkerforge/brickv#26] opened 2023-01-30 07:18 UTC
I am Running Debian Unstable. Last update brought me Python 3.11.1. Since then I get:
````
Traceback (most recent call last):
  File "/usr/share/brickv/main.py", line 75, in <module>
    from PyQt5.Qt import PYQT_VERSION_STR
ImportError: cannot import name 'PYQT_VERSION_STR' from 'PyQt5.Qt' (/usr/lib/python3/dist-packages/PyQt5/Qt.abi3.so)
````
brickv  2.4.23 from TF Repo is installed

**Comment by riesebie** [comment] 2023-01-30 07:56
I want to rebuild the package against  Python 3.11.1 but can't find the Debian source package?

**Comment by photron** [comment] 2023-01-30 16:47
The problem is fixed now. Please update to brickv 2.4.24.

On Debian unstable the PyQt5.Qt module is empty. On Ubuntu and Arch Linux the PyQt5.Qt module contains all the symbols from all the other PyQt5 modules. The PyQt5.Qt module has only been used in tow places in brickv. They have been replaced by an import from the PyQt5.QtCore module. This fixed the problem.

There was no Debian source package, because the brickv Debian package was not build from a proper source package. This has been changed a while back, but since then no new release has been made. The new release now also comes with a Debian source package.

There is no need to try to rebuild the package agains a different Python version, because brickv is pure Python 3 code, and doesn't come with any CPython module.

Thank you for reporting this problem.

**Closed** 2023-01-30 18:42 UTC
